FROM alpine:3.19
LABEL org.opencontainers.image.source=https://github.com/JuanM2209/nucleus-agent
LABEL org.opencontainers.image.description="Nucleus Agent vr23 - Device monitoring & tunneling"
RUN apk add --no-cache ca-certificates util-linux libc6-compat
COPY nucleus-agent /usr/local/bin/nucleus-agent
COPY mbusd /usr/local/bin/mbusd
RUN chmod +x /usr/local/bin/nucleus-agent /usr/local/bin/mbusd
ENTRYPOINT ["nucleus-agent"]
