import { Injectable, Logger } from '@nestjs/common';
import * as fs from 'fs';
import * as path from 'path';

/**
 * Manages the rathole server TOML config file.
 * Rathole has hot-reload enabled — writing the file triggers automatic reload.
 */
@Injectable()
export class RatholeConfigService {
  private readonly logger = new Logger(RatholeConfigService.name);
  private readonly configPath: string;
  private readonly bindAddr: string;
  private readonly defaultToken: string;

  /** In-memory service registry (source of truth for config generation) */
  private readonly services = new Map<string, { bindAddr: string }>();

  constructor() {
    this.configPath = process.env.RATHOLE_CONFIG_PATH
      ?? path.resolve(process.cwd(), '../../infra/rathole/server.toml');
    this.bindAddr = process.env.RATHOLE_BIND_ADDR ?? '0.0.0.0:2333';
    this.defaultToken = process.env.RATHOLE_TOKEN
      ?? 'cde41b29ecba087ace1af210a2cfa88a43d64be1dd64e482019b84fdb137d3a7';

    // Load existing services from config file on startup
    this.loadExistingServices();
  }

  /**
   * Add a service to the rathole server config and write the file.
   */
  addService(serviceName: string, remotePort: number): void {
    this.services.set(serviceName, { bindAddr: `0.0.0.0:${remotePort}` });
    this.writeConfig();
    this.logger.log(`Added service: ${serviceName} → port ${remotePort}`);
  }

  /**
   * Remove a service from the rathole server config and write the file.
   */
  removeService(serviceName: string): void {
    this.services.delete(serviceName);
    this.writeConfig();
    this.logger.log(`Removed service: ${serviceName}`);
  }

  /**
   * Remove multiple services at once (batch cleanup on device disconnect).
   */
  removeServices(serviceNames: string[]): void {
    for (const name of serviceNames) {
      this.services.delete(name);
    }
    if (serviceNames.length > 0) {
      this.writeConfig();
      this.logger.log(`Removed ${serviceNames.length} services`);
    }
  }

  /**
   * Get all active services.
   */
  getServices(): Map<string, { bindAddr: string }> {
    return new Map(this.services);
  }

  /**
   * Generate and write the TOML config. Rathole hot-reloads automatically.
   */
  private writeConfig(): void {
    let toml = `# Rathole Server Configuration — Nucleus Portal V2
# Auto-generated by backend. Rathole hot-reloads on file change.
# DO NOT edit manually — changes will be overwritten.

[server]
bind_addr = "${this.bindAddr}"
default_token = "${this.defaultToken}"

[server.transport]
type = "websocket"

[server.transport.websocket]
tls = false

`;

    // Always include healthcheck placeholder (rathole requires ≥1 service)
    toml += `[server.services.healthcheck]\nbind_addr = "0.0.0.0:10000"\n\n`;

    for (const [name, svc] of this.services) {
      toml += `[server.services."${name}"]\nbind_addr = "${svc.bindAddr}"\n\n`;
    }

    try {
      fs.writeFileSync(this.configPath, toml, 'utf-8');
      this.logger.debug(`Config written: ${this.services.size} services (+ healthcheck)`);
    } catch (err) {
      this.logger.error(`Failed to write rathole config: ${err}`);
    }
  }

  /**
   * Parse existing config file to restore service state on backend restart.
   */
  private loadExistingServices(): void {
    try {
      if (!fs.existsSync(this.configPath)) return;
      const content = fs.readFileSync(this.configPath, 'utf-8');
      const serviceRegex = /\[server\.services\."([^"]+)"\]\s*\nbind_addr\s*=\s*"([^"]+)"/g;
      let match: RegExpExecArray | null;
      while ((match = serviceRegex.exec(content)) !== null) {
        const [, name, bindAddr] = match;
        if (name !== 'healthcheck') {
          this.services.set(name, { bindAddr });
        }
      }
      if (this.services.size > 0) {
        this.logger.log(`Restored ${this.services.size} services from existing config`);
      }
    } catch {
      // Fresh start, no existing config
    }
  }
}
