# Rathole Server — Nucleus Portal V2
# TCP transport — direct connection (not via Cloudflare)

[server]
bind_addr = "0.0.0.0:2333"
default_token = "cde41b29ecba087ace1af210a2cfa88a43d64be1dd64e482019b84fdb137d3a7"

[server.transport]
type = "tcp"

[server.services.healthcheck]
bind_addr = "0.0.0.0:10000"

[server.services."p22-N-1065"]
bind_addr = "0.0.0.0:10001"
