import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Industrial Sentinel Design System
        'surface-container-low': '#131b2e',
        'primary-fixed-dim': '#adc6ff',
        'surface-bright': '#31394d',
        'on-primary': '#002e6a',
        'surface-variant': '#2d3449',
        'primary-fixed': '#d8e2ff',
        'on-surface': '#dae2fd',
        'secondary': '#bcc7de',
        'surface-dim': '#0b1326',
        'on-background': '#dae2fd',
        'outline': '#8c909f',
        'on-primary-fixed': '#001a42',
        'on-primary-container': '#00285d',
        'background': '#0b1326',
        'inverse-on-surface': '#283044',
        'primary-container': '#4d8eff',
        'on-secondary': '#263143',
        'surface-container-lowest': '#060e20',
        'secondary-fixed-dim': '#bcc7de',
        'secondary-fixed': '#d8e3fb',
        'tertiary-fixed': '#6ffbbe',
        'on-secondary-fixed-variant': '#3c475a',
        'primary': '#adc6ff',
        'tertiary': '#4edea3',
        'on-tertiary-container': '#00311f',
        'surface': '#0b1326',
        'inverse-primary': '#005ac2',
        'on-surface-variant': '#c2c6d6',
        'tertiary-container': '#00a572',
        'on-error-container': '#ffdad6',
        'on-tertiary-fixed': '#002113',
        'on-error': '#690005',
        'on-primary-fixed-variant': '#004395',
        'on-tertiary-fixed-variant': '#005236',
        'surface-container-high': '#222a3d',
        'surface-container': '#171f33',
        'error': '#ffb4ab',
        'tertiary-fixed-dim': '#4edea3',
        'surface-container-highest': '#2d3449',
        'error-container': '#93000a',
        'surface-tint': '#adc6ff',
        'on-secondary-fixed': '#111c2d',
        'outline-variant': '#424754',
        'on-tertiary': '#003824',
        'secondary-container': '#3e495d',
        'on-secondary-container': '#aeb9d0',
        'inverse-surface': '#dae2fd',
      },
      fontFamily: {
        headline: ['Manrope', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        label: ['Inter', 'system-ui', 'sans-serif'],
        technical: ['JetBrains Mono', 'monospace'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '1.5rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};

export default config;
