#!/usr/bin/env bash
set -euo pipefail

# ─────────────────────────────────────────────────────────────
# Nucleus Portal V2 — Rathole Server Installer
# Installs rathole server on Linux/macOS for production use
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/JuanM2209/nucleus-portal-v2/main/scripts/install-rathole-server.sh | bash
# ─────────────────────────────────────────────────────────────

RATHOLE_VERSION="0.5.0"
INSTALL_DIR="/opt/nucleus-rathole"
CONFIG_FILE="$INSTALL_DIR/server.toml"
SERVICE_FILE="/etc/systemd/system/rathole-server.service"

echo "╔════════════════════════════════════════════╗"
echo "║  Nucleus Portal V2 — Rathole Server Setup  ║"
echo "╚════════════════════════════════════════════╝"
echo ""

# Detect OS and architecture
OS=$(uname -s | tr '[:upper:]' '[:lower:]')
ARCH=$(uname -m)

case "$OS" in
  linux)
    case "$ARCH" in
      x86_64)  BINARY="rathole-x86_64-unknown-linux-musl" ;;
      aarch64) BINARY="rathole-aarch64-unknown-linux-musl" ;;
      armv7l)  BINARY="rathole-arm-unknown-linux-musleabihf" ;;
      *) echo "ERROR: Unsupported architecture: $ARCH"; exit 1 ;;
    esac
    ;;
  darwin)
    case "$ARCH" in
      x86_64)  BINARY="rathole-x86_64-apple-darwin" ;;
      arm64)   BINARY="rathole-aarch64-apple-darwin" ;;
      *) echo "ERROR: Unsupported architecture: $ARCH"; exit 1 ;;
    esac
    ;;
  *)
    echo "ERROR: Unsupported OS: $OS (use Windows installer for Windows)"
    exit 1
    ;;
esac

DOWNLOAD_URL="https://github.com/rapiz1/rathole/releases/download/v${RATHOLE_VERSION}/${BINARY}.zip"

echo "→ OS: $OS ($ARCH)"
echo "→ Binary: $BINARY"
echo "→ Install dir: $INSTALL_DIR"
echo ""

# Check for root
if [ "$(id -u)" -ne 0 ]; then
  echo "ERROR: This script requires root. Run with sudo:"
  echo "  curl -fsSL <URL> | sudo bash"
  exit 1
fi

# Install dependencies
echo "[1/5] Installing dependencies..."
if command -v apt-get &>/dev/null; then
  apt-get update -qq && apt-get install -y -qq curl unzip >/dev/null
elif command -v yum &>/dev/null; then
  yum install -y -q curl unzip >/dev/null
fi

# Download
echo "[2/5] Downloading rathole v${RATHOLE_VERSION}..."
mkdir -p "$INSTALL_DIR"
curl -fsSL "$DOWNLOAD_URL" -o /tmp/rathole.zip
unzip -o -q /tmp/rathole.zip -d "$INSTALL_DIR"
chmod +x "$INSTALL_DIR/rathole"
rm -f /tmp/rathole.zip

"$INSTALL_DIR/rathole" --version 2>/dev/null || echo "  Binary installed"

# Generate token
echo "[3/5] Generating configuration..."
TOKEN=$(openssl rand -hex 32 2>/dev/null || head -c 64 /dev/urandom | xxd -p | tr -d '\n' | head -c 64)

if [ ! -f "$CONFIG_FILE" ]; then
  cat > "$CONFIG_FILE" << TOML
# Rathole Server — Nucleus Portal V2
# Auto-generated by install script

[server]
bind_addr = "0.0.0.0:2333"
default_token = "$TOKEN"

[server.transport]
type = "tcp"

# Healthcheck placeholder (required by rathole)
[server.services.healthcheck]
bind_addr = "0.0.0.0:10000"

# Dynamic services are added here by the backend
TOML
  echo "  Config created: $CONFIG_FILE"
  echo "  Token: $TOKEN"
  echo ""
  echo "  ⚠  SAVE THIS TOKEN — you need it for agent config"
else
  echo "  Config exists, skipping (delete $CONFIG_FILE to regenerate)"
fi

# Systemd service
echo "[4/5] Creating systemd service..."
if [ "$OS" = "linux" ] && command -v systemctl &>/dev/null; then
  cat > "$SERVICE_FILE" << EOF
[Unit]
Description=Rathole Server (Nucleus Portal V2)
After=network.target

[Service]
Type=simple
ExecStart=$INSTALL_DIR/rathole --server $CONFIG_FILE
Restart=always
RestartSec=5
WorkingDirectory=$INSTALL_DIR
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
EOF

  systemctl daemon-reload
  systemctl enable rathole-server
  systemctl start rathole-server
  echo "  Service created and started"
else
  echo "  Skipping systemd (not available)"
  echo "  Start manually: $INSTALL_DIR/rathole --server $CONFIG_FILE"
fi

# Firewall
echo "[5/5] Configuring firewall..."
if command -v ufw &>/dev/null; then
  ufw allow 2333/tcp comment "Rathole control" >/dev/null 2>&1 || true
  ufw allow 10000:19999/tcp comment "Rathole tunnels" >/dev/null 2>&1 || true
  echo "  UFW rules added"
elif command -v firewall-cmd &>/dev/null; then
  firewall-cmd --permanent --add-port=2333/tcp >/dev/null 2>&1 || true
  firewall-cmd --permanent --add-port=10000-19999/tcp >/dev/null 2>&1 || true
  firewall-cmd --reload >/dev/null 2>&1 || true
  echo "  firewalld rules added"
else
  echo "  No firewall tool found — manually open ports 2333 and 10000-19999"
fi

echo ""
echo "════════════════════════════════════════════"
echo "  Rathole server installed successfully!"
echo ""
echo "  Control channel: 0.0.0.0:2333"
echo "  Dynamic ports:   10000-19999"
echo "  Config:          $CONFIG_FILE"
echo "  Token:           $TOKEN"
echo ""
echo "  Status:  systemctl status rathole-server"
echo "  Logs:    journalctl -u rathole-server -f"
echo "════════════════════════════════════════════"
